{
 "title": "Azure Resource Observability",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Solution",
    "query": "Subscriptions\n| distinct solution"
   },
   {
    "name": "Subscriptions",
    "query": "Subscriptions\n| join Subscription_Names on subscriptionId\n| where solution in ($Solution)\n| extend valueAndText = strcat(subscriptionId, \"|\", name)\n| project valueAndText"
   },
   {
    "name": "Region",
    "query": {
     "query": "let region_1 = Aksservernode_Availability\n| distinct location;\nlet region_2 = Cosmosdb_Availability\n| distinct location;\nlet region_3 = Firewall_Availability\n| distinct location;\nlet region_4 = Keyvault_Availability\n| distinct location;\nlet region_5 = Loadbalancer_Availability\n| distinct location;\nlet region_6 = Storage_Availability\n| distinct location;\nlet region_7 = Cognitive_Svc_Availability\n| distinct location;\nlet region_8 = Container_Registry_Availability\n| distinct location;\nlet region_9 = Eventshub_Availability\n| distinct location;\nunion region_1, region_2, region_3, region_4, region_5, region_6, region_7, region_8, region_9 | distinct *"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource inventory in selected period",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total # of Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Storage_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Storage_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of Aksservernodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Aksservernode_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of LoadBalancers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Loadbalancer_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Loadbalancer_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of Firewalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Firewall_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Firewall_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of Cosmos DBs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Cosmosdb_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cosmosdb_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Note",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "Avg availability of services shown here includes data from all events (platform caused and user errors)"
   },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "vm_availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "loadbalancer_availability\n| where $__timeFilter(['date'])// and region  in ($Region)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of Keyvaults",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Keyvault_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Keyvault_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of Eventshub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Keyvault_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Eventshub_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of CognitiveServices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Keyvault_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total # of ContainerRegistries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Keyvault_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Container_Registry_Availability\n| where $__timeFilter(['date']) and location in ($Region) and subscriptionId in ($Subscriptions)\n| summarize dcount(id)",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "AKS Server Node Avg [(readynode/(readynode+notready))*100]",
   "type": "timeseries",
   "description": "Availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerservicemanagedclusters",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Subscriptions\n|join Aksservernode_Availability on subscriptionId\n| project component, createdAt, ['date'], id, location, name, nodeNotReady,\n nodeReady, nodeUnknown,solution, subscriptionId,tenancy, availability = ((nodeReady )/(nodeNotReady +nodeReady))*100\n| where $__timeFilter(['date'])\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize aksservernode = (avg(availability)) by ['date']",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Container Registry Avg [Successful Tx / All Tx]",
   "type": "timeseries",
   "description": "Availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerservicemanagedclusters",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": {
       "property": {
        "name": "Container_Registry_Availability",
        "type": "string"
       },
       "type": "property"
      },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Subscriptions\n|join Container_Registry_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(successfulPullCount) and isnotnull(totalPullCount)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize acr = (avg(successfulPullCount*100/totalPullCount)) by ['date']",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Avg [Successful Tx / All Tx]",
     "type": "timeseries",
     "description": "Availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccounts",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
     "targets": [
      {
       "database": "sriv04-metricsdb",
       "expression": {
        "from": { "property": { "name": "Storage_Availability", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Subscriptions\n|join Storage_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(availability)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize storage = (avg(availability)) by ['date']",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Balancer Avg [Successful Tx / All Tx]",
     "type": "timeseries",
     "description": "Availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftnetworkazurefirewalls",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
     "targets": [
      {
       "database": "sriv04-metricsdb",
       "expression": {
        "from": { "property": { "name": "Loadbalancer_Availability", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Subscriptions\n|join Loadbalancer_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(availability)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize loadbalancer = (avg(availability)) by ['date']",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Firewall Avg [Successful Tx / All Tx]",
     "type": "timeseries",
     "description": "Availability metric -https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftnetworkazurefirewalls",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 10 },
     "targets": [
      {
       "database": "sriv04-metricsdb",
       "expression": {
        "from": { "property": { "name": "Firewall_Availability", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Subscriptions\n|join Firewall_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(availability)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize firewall = (avg(availability)) by ['date']",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cosmos DB Avg [Successful Tx / All Tx]",
     "type": "timeseries",
     "description": "availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftdocumentdbdatabaseaccounts",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {
       "database": "sriv04-metricsdb",
       "expression": {
        "from": { "property": { "name": "Cosmosdb_Availability", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Subscriptions\n|join Cosmosdb_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(availability)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize cosmosdb = (avg(availability)) by ['date']",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  {
   "title": "Identity + Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Vault Avg [Successful Tx / All Tx]",
     "type": "timeseries",
     "description": "availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftdocumentdbdatabaseaccounts",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
     "targets": [
      {
       "database": "sriv04-metricsdb",
       "expression": {
        "from": { "property": { "name": "Keyvault_Availability", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "Subscriptions\n|join Keyvault_Availability on subscriptionId\n| where $__timeFilter(['date']) and isnotnull(availability)\n and location in ($Region) and subscriptionId in ($Subscriptions)\n and solution in ($Solution)\n| summarize keyvault = (avg(availability)) by ['date']",
       "querySource": "raw"
      }
     ]
    }
   ]
  },
  { "title": "AI + Machine Learning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Cognitive Services[Successful Tx / All Tx]",
   "type": "timeseries",
   "description": "Availability metric - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcontainerservicemanagedclusters",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Subscriptions\r\n|join Cognitive_Svc_Availability on subscriptionId\r\n| where $__timeFilter(['date']) and isnotnull(availability)\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n and solution in ($Solution)\r\n| summarize csa = (avg(availability)) by ['date']",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Eventshub[Successful Tx / All Tx]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "database": "sriv04-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Subscriptions\r\n|join Eventshub_Availability on subscriptionId\r\n| where $__timeFilter(['date']) and isnotnull(incomingRequests) and isnotnull(serverErrors)\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n and solution in ($Solution)\r\n| summarize eventshub = avg((incomingRequests-serverErrors)/incomingRequests)*100 by ['date']",
     "querySource": "raw"
    }
   ]
  }
 ]
}