{
 "title": "Azure Usage Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Solution",
    "query": "Subscriptions\n| distinct solution"
   },
   {
    "name": "Subscriptions",
    "query": "Subscriptions\n| join Subscription_Names on subscriptionId\n| where solution in ($Solution)\n| extend valueAndText = strcat(subscriptionId, \"|\", name)\n| project valueAndText"
   },
   {
    "name": "Region",
    "query": "let region_1 = Aksservernode_Availability\n| distinct location;\nlet region_2 = Cosmosdb_Availability\n| distinct location;\nlet region_3 = Firewall_Availability\n| distinct location;\nlet region_4 = Keyvault_Availability\n| distinct location;\nlet region_5 = Loadbalancer_Availability\n| distinct location;\nlet region_6 = Storage_Availability\n| distinct location;\nlet region_7 = Cognitive_Svc_Availability\n| distinct location;\nlet region_8 = Container_Registry_Availability\n| distinct location;\nlet region_9 = Eventhubs_Availability\n| distinct location;\nunion region_1, region_2, region_3, region_4, region_5, region_6, region_7, region_8, region_9 | distinct *"
   }
  ]
 },
 "panels": [
  { "title": "Deployment by Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model Deployment Count",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| summarize modeldeployments=count_distinct(featurename) by location",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Token count by Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Regional Token Count (GeneratedTokens)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| distinct ['date'], id, generatedtokens, processedprompttokens, inferencetokens, finetunedtraininghours,modeldeploymentname,featurename,subscriptionId,location,name\r\n| summarize sum(generatedtokens) by location",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Regional Token Count (ProcessedPromptTokens)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| distinct ['date'], id, generatedtokens, processedprompttokens, inferencetokens, finetunedtraininghours,modeldeploymentname,featurename,subscriptionId,location,name\r\n| summarize sum(processedprompttokens) by location",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Token Usage Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Token Count Distribution(Stacked Barchart)",
   "type": "barchart",
   "description": " Token count by model name",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| where $__timeFilter(['date'])\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n| summarize sum(processedprompttokens), sum(generatedtokens) by featurename",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Token Count Distribution (Piechart)",
   "type": "piechart",
   "description": " Token count",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| where $__timeFilter(['date'])\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n| summarize sum(processedprompttokens), sum(generatedtokens)",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Latency Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latency by Region",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Latency\r\n| where $__timeFilter(['date'])\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n| summarize avg_latency_in_ms=avg(latency) by location",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Latency by Model",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "targets": [
    {
     "database": "uum07-metricsdb",
     "expression": {
      "from": { "property": { "name": "Aksservernode_Availability_Raw", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Cognitive_Svc_Usage\r\n| where $__timeFilter(['date'])\r\n and location in ($Region) and subscriptionId in ($Subscriptions)\r\n| join kind=inner Cognitive_Svc_Latency on $left.['date']==$right.['date'] and $left.id==$right.id and $left.name==$right.name\r\n| summarize avg_latency_in_ms=avg(latency) by featurename",
     "querySource": "raw"
    }
   ]
  }
 ]
}